### ISSUE TITLE
Crash because explode

### ISSUE THREAD

**Issue by XxAriCoolxX** [Desno365/DesnoGuns-Mod#20] opened 2017-07-14 08:29 UTC
If i using grenade and crossbow explode it will be crash while explode. Plz fix the bug because i love this mod so much

**Comment by Desno365** [comment] 2017-07-14 09:16
Thanks for reporting, the grenade bug it's a known bug and it's caused by Blocklauncher not yet fully updated. While I will investigate more the crossbow explosive bug.

**Comment by Desno365** [comment] 2019-03-05 16:14
Fixed in r025.

**Closed as completed by Desno365** 2019-03-05 16:14 UTC
